/**
 * This file is part of dHealth dApps Framework shared under LGPL-3.0
 * Copyright (C) 2022-present dHealth Network, All rights reserved.
 *
 * @package     dHealth dApps Framework
 * @subpackage  Backend
 * @author      dHealth Network <devs@dhealth.foundation>
 * @license     LGPL-3.0
 */
// external dependencies
import { Injectable } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { OnEvent } from "@nestjs/event-emitter";
import moment from "moment";

// internal dependencies
import { AlertEvent } from "../../common/events/AlertEvent";
import { NotifierFactory } from "../concerns/NotifierFactory";
import { AlertsConfig } from "../../common/models/MonitoringConfig";
import { Notifier } from "../models/Notifier";
import { NotifierType } from "../models/NotifierType";
import { LogService } from "../../common/services/LogService";

/**
 * @class AlertNotifier
 * @description The alert notifier that will send a notification when
 * a warn/error log occurs within the application's api and schedulers.
 * <br /><br />
 * This class is in essential an event listener that listens to and handles
 * warning/error events from the {@link LogService}.
 * <br /><br />
 * When handling events, this class utilizes the {@link Notifier} strategy
 * instance to send notification to specified recipient(s) using configured
 * transport method as defined within {@link AlertsConfig}.
 * <br /><br />
 * Currently this class listens and handles these events:
 * | Name | Description |
 * | --- | --- |
 * | `event.log.warn`     | The event in which a warning log occured in the application. |
 * | `event.log.error`    | The event in which an error log occured in the application. |
 *
 * @todo this class must verify when latest alerts was/were raised
 * @todo it should not send emails every 30 seconds given an error
 * @todo alerts can be differentiated using context and message
 * @since v0.5.0
 */
@Injectable()
export class AlertNotifier {
  /**
   * The configuration object in which specifies the type of
   * event, the notification transport and recipient(s) details.
   *
   * @access private
   * @var {AlertsConfig}
   */
  private readonly alertsConfig: AlertsConfig;

  /**
   * The {@link Notifier} strategy of this class. Depending on
   * the transport method specified in the {@link ReportsConfig}
   * this will be generated by the {@link NotifierFactory}.
   *
   * @access private
   * @var {Notifier}
   */
  private readonly notifier: Notifier;

  /**
   * Constructs and prepares an instance of this class.
   *
   * @param {ConfigService}   configService
   * @param {NotifierFactory} notifierFactory
   */
  constructor(
    private readonly configService: ConfigService,
    private readonly notifierFactory: NotifierFactory,
  ) {
    // get config
    this.alertsConfig = this.configService.get<AlertsConfig>("alerts");

    // get the notifier strategy from the configured transport method
    this.notifier = this.notifierFactory.getNotifier(
      this.alertsConfig.transport as NotifierType,
    );
  }

  /**
   * Main method to handle `notifier.alerts.warn` event.
   *
   * @access protected
   * @param event
   * @return {void}
   */
  @OnEvent("notifier.alerts.warn", { async: true })
  protected async handleLogWarnEvent(event: AlertEvent): Promise<void> {
    // handle and process "AlertEvent" event
    if (this.alertsConfig.type.includes("warn")) {
      const dappName = this.configService.get<string>("dappName");
      const dappUrl = this.configService.get<string>("frontendApp.url");
      const { timestamp, level, loggerContext, message, context } = event;
      const dateFormat = moment(new Date()).format("YYYY-MM-DD hh:mm:ss");
      await this.notifier.sendInternal({
        to: this.alertsConfig.recipient,
        subject: `[${dappName}] WARNING on dApp (${dappUrl}) at ${dateFormat}`,
        template: "AlertEmailTemplate", // The `.pug` or `.hbs` extension is appended automatically.
        context: {
          // Data to be sent to template engine.
          alertLevel: "WARNING",
          dappUrl,
          dateFormat,
          details: { timestamp, level, loggerContext, message, context },
        },
      });
    }
  }

  /**
   * Main method to handle `notifier.alerts.error` event.
   *
   * @access protected
   * @param event
   * @return {void}
   */
  @OnEvent("notifier.alerts.error", { async: true })
  protected async handleLogErrorEvent(event: AlertEvent): Promise<void> {
    // handle and process "AlertEvent" event
    if (this.alertsConfig.type.includes("error")) {
      const dappName = this.configService.get<string>("dappName");
      const dappUrl = this.configService.get<string>("frontendApp.url");
      const { timestamp, level, loggerContext, message, trace, context } =
        event;
      const dateFormat = moment(new Date()).format("YYYY-MM-DD hh:mm:ss");
      await this.notifier.sendInternal({
        to: this.alertsConfig.recipient,
        subject: `[${dappName}] ERROR on dApp (${dappUrl}) at ${dateFormat}`,
        template: "AlertEmailTemplate", // The `.pug` or `.hbs` extension is appended automatically.
        context: {
          // Data to be sent to template engine.
          alertLevel: "ERROR",
          dappUrl,
          dateFormat,
          details: { timestamp, level, loggerContext, message, trace, context },
        },
      });
    }
  }
}
