version: '3.7'

services:
  frontend:
    user: '1000:1000'
    container_name: dapp-frontend
    build:
      context: runtime/dapp-frontend-vue
      target: production
    ports:
      - ${FRONTEND_PORT}:8080
    env_file:
      - runtime/dapp-frontend-vue/.env
    command: npm run serve:prod
    networks:
      - dapp-net

  backend:
    user: '1000:1000'
    container_name: dapp-backend
    build:
      context: runtime/backend
      target: production
    ports:
      - ${BACKEND_PORT}:7903
    env_file:
      - .env
    command: npm run start:prod
    volumes:
      - ./runtime/backend/logs:/logs
    networks:
      - dapp-net
    depends_on:
      - mongodb

  mongodb:
    user: '1000:1000'
    container_name: dapp-database
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
      MONGO_INITDB_DATABASE: $DB_NAME
    volumes:
      - ./runtime/backend/data:/data/db
    networks:
      - dapp-net
    ports:
      - "127.0.0.1:27017:27017"

networks:
  dapp-net:
    driver: bridge
