version: '3.7'

services:
  main:
    container_name: dapp-backend-app
    build:
      context: .
      target: production
    ports:
      - ${PROD_APP_PORT}:7903
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
    command: npm run start:prod
    networks:
      - dapp-net
    depends_on:
      - mongodb

  mongodb:
    container_name: dapp-backend-db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
      MONGO_INITDB_DATABASE: $DB_NAME
    volumes:
      - ./data:/data/db
    networks:
      - dapp-net
    ports:
      - "127.0.0.1:27017:27017"

networks:
  dapp-net:
    driver: bridge
