/**
 * This file is part of dHealth dApps Framework shared under LGPL-3.0
 * Copyright (C) 2022-present dHealth Network, All rights reserved.
 *
 * @package     dHealth dApps Framework
 * @subpackage  Backend
 * @author      dHealth Network <devs@dhealth.foundation>
 * @license     LGPL-3.0
 */
// external dependencies
import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { Model, FilterQuery } from "mongoose";
import { ObjectLiteral } from "@dhealth/contracts";

// internal dependencies
// common scope
import { Documentable } from "../../common/concerns/Documentable";
import { Transferable } from "../../common/concerns/Transferable";
import { Queryable, QueryParameters } from "../../common/concerns/Queryable";

// common/models
import { AssetsConfig } from "../../common/models/AssetsConfig";

// users scope
import { ActivityDTO } from "./ActivityDTO";
import { ActivityData, ActivityDataSchema } from "./ActivityDataSchema";
import { ProcessingState } from "./ProcessingStatusDTO";

// payout scope
import { PayoutState } from "../../payout/models/PayoutStatusDTO";

/**
 * @class Activity
 * @description This class defines the **exact** fields that are
 * stored in the corresponding MongoDB documents. It should be
 * used whenever database *documents* are being handled or read
 * for the `activities` collection.
 * <br /><br />
 * Note that this class uses the generic {@link Transferable} trait to
 * enable a `toDTO()` method on the model.
 *
 * @todo Timestamp fields should be **numbers** to avoid timezone issues.
 * @since v0.3.2
 */
@Schema({
  timestamps: true,
})
export class Activity extends Transferable<ActivityDTO> {
  /**
   * This field contains the *mongo collection name* for entries
   * that are stored using {@link ActivityDocument} or the model
   * {@link ActivityModel}.
   * <br /><br />
   * Note that this field **is not** part of document properties
   * and used only internally to perform queries that refer to
   * an individual collection name, e.g. `$unionWith`.
   *
   * @access public
   * @var {string}
   */
  public collectionName = "activities";

  /**
   * The account's **address**. An address typically refers to a
   * human-readable series of 39 characters, starting either with
   * a `T`, for TESTNET addresses, or with a `N`, for MAINNET addresses.
   * <br /><br />
   * This field is **required** and *indexed*.
   *
   * @access public
   * @readonly
   * @var {string}
   */
  @Prop({ required: true, index: true })
  public readonly address: string;

  /**
   * The activity identifier is a remote (external) identifier that
   * is generated by the data provider and shared to *uniquely*
   * identify the activity on the side of the data provider.
   * <br /><br />
   * This field is **required** and *indexed* and must hold
   * a *unique* value.
   *
   * @access public
   * @readonly
   * @var {string}
   */
  @Prop({ required: true, index: true, unique: true, type: String })
  public readonly remoteIdentifier: string;

  /**
   * The activity slug is composed of the date of the activity,
   * the index of it on a daily basis, the activity identifier
   * and the athlete identifier.
   * <br /><br />
   * This field is **required** and *indexed* and must hold
   * a *unique* value.
   *
   * @access public
   * @readonly
   * @var {string}
   */
  @Prop({ required: true, index: true, unique: true, type: String })
  public readonly slug: string;

  /**
   * The activity's *date slug* consists of a `YYYYMMDD` formatted
   * date and is used to *prefix* individual activity slugs.
   * <br /><br />
   * This field is **required** and *indexed*.
   *
   * @access public
   * @readonly
   * @var {string}
   */
  @Prop({ required: true, index: true })
  public readonly dateSlug: string;

  /**
   * The OAuth provider name. This is usually the name of the
   * platform of which an account has completed an activity.
   * <br /><br />
   * This field is **required** and *not indexed*.
   *
   * @access public
   * @readonly
   * @var {string}
   */
  @Prop({ required: true })
  public readonly provider: string;

  /**
   * This is the activity mosaics as defined by dHealth Network. It
   * contains an array of `ObjectLiteral` objects that consist of both
   * a *mosaicId* and *amount* field.
   * <br /><br />
   * This field contains the actual *tokens* that have been paid out
   * to the end-user for this activity. It can hold only a single
   * mosaic or up to 10 different mosaics that were sent to the end-
   * user for completing this activity.
   * <br /><br />
   * This field is **optional**, *indexed* and defaults to an empty
   * array.
   *
   * @example `[{ "mosaicId": "39E0C49FA322A459", amount: 1 }]`
   * @access public
   * @readonly
   * @var {string}
   */
  @Prop({ required: false, type: [Object], index: true, default: [] })
  public readonly activityAssets?: ObjectLiteral[];

  /**
   * This is the activity data as processed from the data provider. It
   * contains an object that consists of the *activity data*.
   * <br /><br />
   * This object may represent [some] parts of an end-users Patient Health
   * Record, as such it is important that this data is not accessible to
   * unauthorized users.
   * <br /><br />
   * This field is **optional**, *not indexed* and defaults to `null`.
   *
   * @example `{ "sport": "Run", calories: 1000 }`
   * @access public
   * @readonly
   * @var {string}
   */
  @Prop({ nullable: true, type: ActivityDataSchema, default: null })
  public readonly activityData?: ActivityData;

  /**
   * This property is a flag that determines whether the activity has been
   * *processed* by the processor before. An activity is considered to be
   * *fully processed* only *after* the full details (activity data) has
   * been downloaded from the data provider.
   * <br /><br />
   * Possible values for this field in the database are of type `number` and
   * listed in {@link ProcessingState}. Initially, the value will always be
   * `0` as this corresponds to "not-processed".
   * <br /><br />
   * This field is **optional**, *indexed* and defaults to `0`.
   *
   * @example `0`
   * @access public
   * @readonly
   * @var {ProcessingState}
   */
  @Prop({ required: true, index: true, default: 0 })
  public readonly processingState?: ProcessingState;

  /**
   * This property is a flag that determines whether the activity payout
   * has been executed. An activity is considered to be *completed* only
   * *after* the payout has been *confirmed* on dHealth Network.
   * <br /><br />
   * Possible values for this field in the database are of type `number` and
   * listed in {@link PayoutState}. Initially, the value will always be
   * `0` as this corresponds to "not-started".
   * <br /><br />
   * This field is **optional**, *indexed* and defaults to `0`.
   *
   * @example `0`
   * @access public
   * @readonly
   * @var {PayoutState}
   */
  @Prop({ required: true, index: true, default: 0 })
  public readonly payoutState?: PayoutState;

  /**
   * The document's creation timestamp. This field **does not** represent an
   * activity's actual date of creation but rather the date of creation of
   * the cached database entry.
   * <br /><br />
   * For details about an activity's *starting* time, please refer to the
   * {@link ActivityDataSchema} model instead.
   *
   * @access public
   * @readonly
   * @var {Date}
   */
  @Prop({ index: true })
  public readonly createdAt?: Date;

  /**
   * The document's update timestamp. This field **does not** reflect the
   * date of update of an integration but rather the date of update of the
   * cached database entry.
   *
   * @access public
   * @readonly
   * @var {Date}
   */
  @Prop()
  public readonly updatedAt?: Date;

  /**
   * Activity type field.
   * Gets populated once user completes an activity.
   * <br /><br />
   * This field is **required** and *not indexed*.
   *
   * @example `"swim"`
   * @access public
   * @var {string}
   */
  @Prop({ default: "" })
  public sport: string;

  /**
   * This property represents time that user spent
   * on completing activity.
   * <br /><br />
   * This field is **required** and *not indexed*.
   *
   * @example `"swim"`
   * @access public
   * @var {string}
   */
  @Prop({ default: 0 })
  public elapsedTime: number;

  /**
   * This field represents distance user completed during an activity.
   * <br /><br />
   * This field is **required** and *not indexed*.
   *
   * @example `"swim"`
   * @access public
   * @var {string}
   */
  @Prop({ default: 0 })
  public distance: number;

  /**
   * This property represents an elevation gain
   * <br /><br />
   * This field is **required** and *not indexed*.
   *
   * @example `"swim"`
   * @access public
   * @var {string}
   */
  @Prop({ default: 0 })
  public elevationGain: number;

  /**
   * This method implements a specialized query format to query items
   * individually, as documents, in the collection: `account_integrations`.
   *
   * @access public
   * @returns {Record<string, unknown>}    The individual document data that is used in a query.
   */
  public get toQuery(): Record<string, unknown> {
    const query: Record<string, any> = {};

    if (undefined !== this.address) query["address"] = this.address;
    if (undefined !== this.slug) query["slug"] = this.slug;
    if (undefined !== this.dateSlug) query["dateSlug"] = this.dateSlug;
    if (undefined !== this.remoteIdentifier)
      query["remoteIdentifier"] = this.remoteIdentifier;
    if (undefined !== this.processingState)
      query["processingState"] = this.processingState;
    if (undefined !== this.payoutState) query["payoutState"] = this.payoutState;

    return query;
  }

  /**
   * This *static* method populates a {@link ActivityDTO} object from the
   * values of a {@link ActivityDocument} as presented by mongoose queries.
   *
   * @access public
   * @static
   * @param   {ActivityDocument}   doc   The document as received from mongoose.
   * @param   {ActivityDTO}        dto   The DTO object that will be populated with values.
   * @returns {ActivityDTO}        The `dto` object with fields set.
   */
  public static fillDTO(doc: ActivityDocument, dto: ActivityDTO): ActivityDTO {
    dto.address = doc.address;
    dto.slug = doc.slug;
    if (doc.activityData) {
      dto.assets = doc.activityAssets;
      dto.distance = doc.activityData.distance;
      dto.sport = doc.activityData.sport;
      dto.elevationGain = doc.activityData.elevation;
      dto.elapsedTime = doc.activityData.elapsedTime;
      dto.provider = doc.provider;
    }
    return dto;
  }
}

/**
 * @type ActivityDocument
 * @description This type is used to interface entities of the
 * `activities` collection with *mongoose* and permits to
 * an instance and objects representing these entities.
 * <br /><br />
 * e.g. alongside {@link ActivitySchema}, we also define
 * `ActivityDocument` which is a mixin that comprises of
 * {@link Activity} and this `Documentable` class.
 * <br /><br />
 * In class {@link Queryable}, the first generic accepted
 * permits to use *documents* that are typed with this, to filter
 * results in a documents query.
 *
 * @since v0.3.0
 */
export type ActivityDocument = Activity & Documentable;

/**
 * @class ActivityModel
 * @description This class defines the **model** or individual
 * **document** for one collection ("schema"). This class can
 * be *automatically* injected in services using the `@InjectModel`
 * decorator of `nestjs/mongoose`.
 * <br /><br />
 * @example Injecting and using the `ActivityModel`
 * ```typescript
 *   import { InjectModel } from "@nestjs/mongoose";
 *   import { Activity, ActivityModel } from "./ActivitySchema";
 *
 *   class MyActivityService {
 *     public constructor(
 *       @InjectModel(Activity.name) private readonly model: ActivityModel
 *     )
 *
 *     public addEntry(data: Record<string, any>) {
 *       return this.model.create(data);
 *     }
 *   }
 * ```
 *
 * @since v0.3.0
 */
export class ActivityModel extends Model<ActivityDocument> {}

/**
 * @class ActivityQuery
 * @description This class augments {@link Queryable} objects enabling
 * *activities* to be queried **by `address`** and **by `transactionsCount`.**
 * <br /><br />
 * The main purpose of this class shall be to perform queries against
 * the `activities` collection.
 *
 * @since v0.3.0
 */
export class ActivityQuery extends Queryable<ActivityDocument> {
  /**
   * Copy constructor for pageable queries in `activities` collection.
   *
   * @see Queryable
   * @param   {ActivityDocument|undefined}     document          The *document* instance (defaults to `undefined`) (optional).
   * @param   {QueryParameters|undefined}     queryParameters   The query parameters including as defined in {@link QueryParameters} (optional).
   */
  public constructor(
    document?: ActivityDocument,
    queryParams: QueryParameters = undefined,
    filterQuery?: FilterQuery<ActivityDocument>,
  ) {
    super(document, queryParams);
  }
}

/**
 * @export ActivitySchema
 * @description This export creates a mongoose schema using the custom
 * {@link Activity} class and should be used mainly when *inferring* the
 * type of fields in a document for the corresponding collection.
 *
 * @since v0.3.0
 */
export const ActivitySchema = SchemaFactory.createForClass(Activity);

// This call to **loadClass** on the schema object enables instance
// methods on the {@link Activity} class to be called when the model gets
// instanciated by `mongoose` directly, e.g. as the result of a query.
ActivitySchema.loadClass(Activity, true);
