/**
 * This file is part of dHealth dApps Framework shared under LGPL-3.0
 * Copyright (C) 2022-present dHealth Network, All rights reserved.
 *
 * @package     dHealth dApps Framework
 * @subpackage  Backend
 * @author      dHealth Network <devs@dhealth.foundation>
 * @license     LGPL-3.0
 */
// external dependencies
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { ApiProperty } from '@nestjs/swagger';
import { Document } from 'mongoose';

// export type AccountDocument as a combination of Account & Document classes
export type AccountDocument = Account & Document;

/**
 * @class Account
 * @description The main MongoDB schema for Account.
 *
 * @since v0.1.0
 */
@Schema({
  // enable timestamps
  timestamps: true,
})
export class Account {
  /**
   * Account's ID.
   * This will be auto-generated by Mongo.
   *
   * @var {string}
   */
  @ApiProperty()
  _id?: string;

  /**
   * Account's wallet address.
   *
   * @var {string}
   */
  @ApiProperty()
  @Prop({ required: true })
  address: string;

  /**
   * Account's transaction count.
   * Measures the total number of transactions it has received from dapp account.
   *
   * @var {number}
   */
  @ApiProperty()
  @Prop()
  transactionsCount?: number;

  /**
   * Account's first transaction date.
   * This is the date of the first transaction it received from dapp account.
   *
   * @var {Date}
   */
  @ApiProperty()
  @Prop()
  firstTransactionAt?: Date;

  /**
   * Account's first transaction block.
   * The block height that this account's first transaction got confirmed.
   *
   * @var {number}
   */
  @ApiProperty()
  @Prop()
  firstTransactionAtBlock?: number;
}

// export AccountSchema
export const AccountSchema = SchemaFactory.createForClass(Account);
