/**
 * This file is part of dHealth dApps Framework shared under LGPL-3.0
 * Copyright (C) 2022-present dHealth Network, All rights reserved.
 *
 * @package     dHealth dApps Framework
 * @subpackage  Backend
 * @author      dHealth Network <devs@dhealth.foundation>
 * @license     LGPL-3.0
 */
// external dependencies
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';

// internal dependencies
import { StateData } from './state.dto';

// export type StateDocument as a combination of State & Document classes
export type StateDocument = State & Document;

/**
 * @class State
 * @description The main MongoDB schema for State.
 *
 * @since v0.1.0
 */
@Schema({
  // enable timestamps
  timestamps: true,
})
export class State {
  /**
   * State's ID.
   * This will be auto-generated by Mongo.
   *
   * @var {string}
   */
  _id?: string;

  /**
   * State's name.
   *
   * @var {string}
   */
  @Prop({ required: true })
  name: string;

  /**
   * State's data.
   * This is the data of the state.
   *
   * @var {StateData}
   */
  @Prop({ required: true, type: Object })
  data: StateData;
}

// export StateSchema
export const StateSchema = SchemaFactory.createForClass(State);
